version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - database
    command: >
      /bin/sh -c 'echo {\"postgres\": {\"host\":\"database\" }} > /dist/config.json
      && cat /dist/config.json
      && /dist/main'

