version: '2.1'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tasksuser -d tasks" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy
    command: >
      /bin/sh -c 'goose -dir /dist/migrations postgres "user=tasksuser password=password123431 host=database dbname=tasks sslmode=disable" up
      && echo {\"postgres\": {\"host\":\"database\" }} > /dist/config.json
      && cat /dist/config.json
      && /dist/main'

